-- =========================================================================
-- COMPLETE MIGRATION & SEED: Motorcycle Models
-- I-paste at i-run ito sa Supabase Dashboard > SQL Editor
-- Magkakaroon agad ng 185 models ang database kahit walang Node backend!
-- =========================================================================

-- 1. Create table
CREATE TABLE IF NOT EXISTS public.motorcycle_models (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand VARCHAR(60) NOT NULL,
  name VARCHAR(160) NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Create search indexes
CREATE INDEX IF NOT EXISTS idx_motorcycle_models_name ON public.motorcycle_models(name);
CREATE INDEX IF NOT EXISTS idx_motorcycle_models_brand ON public.motorcycle_models(brand);

-- 3. Enable RLS
ALTER TABLE public.motorcycle_models ENABLE ROW LEVEL SECURITY;

-- 4. Allow public reading
DROP POLICY IF EXISTS "Allow public read access to active motorcycle models" ON public.motorcycle_models;
CREATE POLICY "Allow public read access to active motorcycle models" 
  ON public.motorcycle_models 
  FOR SELECT 
  USING (is_active = true);

-- 5. Insert all 185 popular Philippine motorcycle models
INSERT INTO public.motorcycle_models (brand, name)
VALUES
  ('Honda', 'Honda Click 125 (V1 / V2 / V3)'),
  ('Honda', 'Honda Click 150 / 160'),
  ('Honda', 'Honda Beat 110 (Carb / Fi)'),
  ('Honda', 'Honda PCX 150 / 160'),
  ('Honda', 'Honda ADV 150 / 160'),
  ('Honda', 'Honda Genio 110 / Scoopy'),
  ('Honda', 'Honda Zoomer-X 110'),
  ('Honda', 'Honda Wave 100 / 110 Alpha / 125'),
  ('Honda', 'Honda XRM 110 / 125 (Carb / Fi / Motard)'),
  ('Honda', 'Honda RS125 Fi'),
  ('Honda', 'Honda Winner X 150 / Supra GTR'),
  ('Honda', 'Honda TMX 125 Alpha'),
  ('Honda', 'Honda TMX 155 (Classic CDI / Contact Point)'),
  ('Honda', 'Honda Super Cub C125 / CT125 Hunter Cub'),
  ('Honda', 'Honda Dream 100 / C70 (Vintage)'),
  ('Honda', 'Honda XR150L / XR200'),
  ('Honda', 'Honda CRF150L / CRF250L / CRF300L / Rally'),
  ('Honda', 'Honda CBR150R / CB150R / CB150X'),
  ('Honda', 'Honda CB400 Super Four (Project Big 1)'),
  ('Honda', 'Honda CB500X / NX500 / CBR500R'),
  ('Honda', 'Honda Rebel 500 / Rebel 1100'),
  ('Honda', 'Honda CB650R / CBR650R'),
  ('Honda', 'Honda Transalp XL750'),
  ('Honda', 'Honda X-ADV 750 / Forza 350 / 750'),
  ('Honda', 'Honda Africa Twin CRF1100L'),
  ('Honda', 'Honda CBR1000RR Fireblade'),
  ('Honda', 'Honda Gold Wing 1800'),
  ('Yamaha', 'Yamaha NMAX 155 (V1 / V2 / V3)'),
  ('Yamaha', 'Yamaha Aerox 155 (V1 / V2)'),
  ('Yamaha', 'Yamaha Mio Sporty / Amore'),
  ('Yamaha', 'Yamaha Mio i 125 (M3)'),
  ('Yamaha', 'Yamaha Mio Soul / Soul i 115 / 125'),
  ('Yamaha', 'Yamaha Mio Gravis 125'),
  ('Yamaha', 'Yamaha Mio Fazzio 125'),
  ('Yamaha', 'Yamaha Mio Gear 125'),
  ('Yamaha', 'Yamaha Sniper 135 (Classic)'),
  ('Yamaha', 'Yamaha Sniper 150 (MXi / King)'),
  ('Yamaha', 'Yamaha Sniper 155 / 155R'),
  ('Yamaha', 'Yamaha Sight 115 / Vega Force Fi'),
  ('Yamaha', 'Yamaha Crypton 100 / 110 (Classic)'),
  ('Yamaha', 'Yamaha YTX 125'),
  ('Yamaha', 'Yamaha RS100 / RX100 / RX-T 135 (2-Stroke)'),
  ('Yamaha', 'Yamaha DT125 Enduro (Classic)'),
  ('Yamaha', 'Yamaha WR 155R / Serow 250'),
  ('Yamaha', 'Yamaha XSR 155 / MT-15 / TFX 150'),
  ('Yamaha', 'Yamaha YZF-R15 (V1 / V2 / V3 / V4)'),
  ('Yamaha', 'Yamaha YZF-R3 / MT-03'),
  ('Yamaha', 'Yamaha XMAX 300 / TMAX 560'),
  ('Yamaha', 'Yamaha MT-07 / YZF-R7 / Tenere 700'),
  ('Yamaha', 'Yamaha MT-09 / Tracer 9 GT / XSR 900'),
  ('Yamaha', 'Yamaha YZF-R1 / R1M / MT-10'),
  ('Suzuki', 'Suzuki Raider R150 Carburetor'),
  ('Suzuki', 'Suzuki Raider R150 Fi'),
  ('Suzuki', 'Suzuki Raider J 110 / 115 Fi / Crossover'),
  ('Suzuki', 'Suzuki Smash 110 (Classic) / Smash 115'),
  ('Suzuki', 'Suzuki Shogun 125 / Shogun Pro'),
  ('Suzuki', 'Suzuki Burgman Street 125 / Street EX'),
  ('Suzuki', 'Suzuki Avenis 125'),
  ('Suzuki', 'Suzuki Skydrive 125 / Skydrive Sport / Crossover'),
  ('Suzuki', 'Suzuki Step 125 / Address 110'),
  ('Suzuki', 'Suzuki GD110 / Thunder 125'),
  ('Suzuki', 'Suzuki Gixxer 150 / Gixxer 250 / SF 250'),
  ('Suzuki', 'Suzuki GSX-R150 / GSX-S150'),
  ('Suzuki', 'Suzuki V-Strom 250SX / V-Strom 650 XT'),
  ('Suzuki', 'Suzuki SV650 / SV650X'),
  ('Suzuki', 'Suzuki GSX-8S / GSX-8R / V-Strom 800DE'),
  ('Suzuki', 'Suzuki GSX-S750 / GSX-R750'),
  ('Suzuki', 'Suzuki GSX-R1000 / GSX-S1000 / Katana'),
  ('Suzuki', 'Suzuki Hayabusa (GSX-1300R)'),
  ('Kawasaki', 'Kawasaki Barako I / II 175'),
  ('Kawasaki', 'Kawasaki CT100 / CT125 / CT150'),
  ('Kawasaki', 'Kawasaki HD3 / GTO 125 (Classic 2-Stroke)'),
  ('Kawasaki', 'Kawasaki Fury 125 / 125R / Curve 115'),
  ('Kawasaki', 'Kawasaki KLX 140 / 150 / 230 / 300'),
  ('Kawasaki', 'Kawasaki D-Tracker 150 / 250'),
  ('Kawasaki', 'Kawasaki Rouser NS125 / NS160 / NS200'),
  ('Kawasaki', 'Kawasaki Rouser 135LS / 180 / 220'),
  ('Kawasaki', 'Kawasaki Dominar 400 (V1 / UG)'),
  ('Kawasaki', 'Kawasaki Ninja 300 / 400 / 500'),
  ('Kawasaki', 'Kawasaki Ninja ZX-4RR / ZX-6R'),
  ('Kawasaki', 'Kawasaki Z400 / Z500 / Z650 / Ninja 650'),
  ('Kawasaki', 'Kawasaki Vulcan S 650 / W800'),
  ('Kawasaki', 'Kawasaki Versys-X 300 / Versys 650 / 1000'),
  ('Kawasaki', 'Kawasaki Z900 / Z900RS / Z1000'),
  ('Kawasaki', 'Kawasaki Ninja ZX-10R / Ninja H2'),
  ('Rusi', 'Rusi Classic 250 (RC250)'),
  ('Rusi', 'Rusi Classic 400'),
  ('Rusi', 'Rusi Mojo 200 (Scrambler)'),
  ('Rusi', 'Rusi Titan 250'),
  ('Rusi', 'Rusi Ripcord 250'),
  ('Rusi', 'Rusi Flash 150 (Scooter)'),
  ('Rusi', 'Rusi Rapid 150'),
  ('Rusi', 'Rusi Gala 125'),
  ('Rusi', 'Rusi Passion 125'),
  ('Rusi', 'Rusi Sigma 250'),
  ('Rusi', 'Rusi RFI 175'),
  ('Rusi', 'Rusi TC 125 / TC 150 (Tricycle Backbone)'),
  ('Rusi', 'Rusi Korak Plus 110'),
  ('Rusi', 'Rusi Macho 125 / 150'),
  ('Rusi', 'Rusi Gremlin 110 / SSX 200'),
  ('Motorstar', 'Motorstar Cafe 400'),
  ('Motorstar', 'Motorstar Star-X 125 / 155'),
  ('Motorstar', 'Motorstar Z-One 150 / Hawk 150'),
  ('Motorstar', 'Motorstar MSX 125 / Easycamper 150'),
  ('Skygo', 'Skygo Boss 150 / King 150'),
  ('Skygo', 'Skygo Earl 150 / Pony 100 / Archer 125'),
  ('Kymco', 'Kymco Like 125 / 150i (Noodoe)'),
  ('Kymco', 'Kymco KRV 180i TCS'),
  ('Kymco', 'Kymco Super 8 125 / 150'),
  ('Kymco', 'Kymco Dink R 150 / Racing King 180'),
  ('Kymco', 'Kymco X-Town 300Fi / Downtown 350'),
  ('Kymco', 'Kymco Xciting S 400 / AK550'),
  ('SYM', 'SYM Bonus 110 / Bonus X'),
  ('SYM', 'SYM Jet 14 150 / 200'),
  ('SYM', 'SYM Cruisym 150 / 300'),
  ('SYM', 'SYM Husky ADV 150'),
  ('SYM', 'SYM Maxsym 400 / Maxsym TL 508'),
  ('Vespa', 'Vespa Sprint 150 / Carbon'),
  ('Vespa', 'Vespa Primavera 150'),
  ('Vespa', 'Vespa GTS 300 Super Sport / HPE'),
  ('Vespa', 'Vespa S 125 / LX 125 / GTV 300'),
  ('Bajaj', 'Bajaj CT100 / CT125 / CT150 Boxer'),
  ('Bajaj', 'Bajaj Pulsar NS160 / NS200'),
  ('Bajaj', 'Bajaj RE 3-Wheeler / Maxima Z'),
  ('TVS', 'TVS Ntorq 125'),
  ('TVS', 'TVS Dazz 110 / Neo XR 110'),
  ('TVS', 'TVS Apache RTR 160 / 200 4V / RR310'),
  ('TVS', 'TVS Ronin 225'),
  ('CFMOTO', 'CFMOTO Papio XO-1 / XO-2'),
  ('CFMOTO', 'CFMOTO 300SR / 300NK'),
  ('CFMOTO', 'CFMOTO 450SR / 450SR-S'),
  ('CFMOTO', 'CFMOTO 450NK / 450CL-C'),
  ('CFMOTO', 'CFMOTO 450MT (Adventure)'),
  ('CFMOTO', 'CFMOTO 650NK / 650MT / 650GT'),
  ('CFMOTO', 'CFMOTO 700CL-X (Heritage / Sport / ADV)'),
  ('CFMOTO', 'CFMOTO 800MT (Sport / Touring / Explore)'),
  ('CFMOTO', 'CFMOTO 800NK'),
  ('Bristol', 'Bristol Classic 400 / Omega 400'),
  ('Bristol', 'Bristol BR 400i / Bobber 650'),
  ('Bristol', 'Bristol Veloce 500 / Venturi 500'),
  ('Bristol', 'Bristol Assassin 400 / ADX 160'),
  ('Benelli', 'Benelli Leoncino 250 / 500 / Trail'),
  ('Benelli', 'Benelli TRK 502 / 502X / 502C Cruiser'),
  ('Benelli', 'Benelli TNT 135 / Imperiale 400'),
  ('QJ Motor', 'QJ Motor SRV 200 / SRV 400'),
  ('QJ Motor', 'QJ Motor SRK 400 / SRK 600 / SRT 800'),
  ('KTM', 'KTM Duke 200 / Duke 390'),
  ('KTM', 'KTM RC 200 / RC 390'),
  ('KTM', 'KTM 390 Adventure'),
  ('KTM', 'KTM 790 Duke / 890 Duke R'),
  ('KTM', 'KTM 790 Adventure / 890 Adventure R'),
  ('KTM', 'KTM 1290 Super Duke R / Super Adventure'),
  ('Husqvarna', 'Husqvarna Svartpilen 200 / 401'),
  ('Husqvarna', 'Husqvarna Vitpilen 401 / Norden 901'),
  ('Royal Enfield', 'Royal Enfield Classic 350 / Bullet 350'),
  ('Royal Enfield', 'Royal Enfield Hunter 350 / Meteor 350'),
  ('Royal Enfield', 'Royal Enfield Himalayan 411 / Himalayan 450'),
  ('Royal Enfield', 'Royal Enfield Scram 411'),
  ('Royal Enfield', 'Royal Enfield Interceptor 650 / Continental GT 650'),
  ('Royal Enfield', 'Royal Enfield Super Meteor 650 / Shotgun 650'),
  ('BMW', 'BMW G 310 R / G 310 GS'),
  ('BMW', 'BMW C 400 X / GT'),
  ('BMW', 'BMW F 750 GS / F 850 GS / F 900 R / XR'),
  ('BMW', 'BMW R 1200 GS / R 1250 GS Adventure'),
  ('BMW', 'BMW R 1300 GS'),
  ('BMW', 'BMW R nineT / R 12'),
  ('BMW', 'BMW S 1000 RR / S 1000 R / S 1000 XR'),
  ('Ducati', 'Ducati Monster 797 / 821 / 937'),
  ('Ducati', 'Ducati Scrambler 800 (Icon / Full Throttle)'),
  ('Ducati', 'Ducati Hypermotard 950'),
  ('Ducati', 'Ducati Streetfighter V2 / V4'),
  ('Ducati', 'Ducati Panigale V2 / V4 / V4S'),
  ('Ducati', 'Ducati Multistrada 950 / V2 / V4'),
  ('Ducati', 'Ducati Diavel 1260 / Diavel V4'),
  ('Triumph', 'Triumph Trident 660 / Tiger Sport 660'),
  ('Triumph', 'Triumph Street Triple 765 R / RS'),
  ('Triumph', 'Triumph Bonneville T100 / T120'),
  ('Triumph', 'Triumph Scrambler 900 / 1200'),
  ('Triumph', 'Triumph Tiger 900 / 1200'),
  ('Harley-Davidson', 'Harley-Davidson Iron 883 / Forty-Eight'),
  ('Harley-Davidson', 'Harley-Davidson Street 750 / Street Rod'),
  ('Harley-Davidson', 'Harley-Davidson Sportster S 1250 / Nightster'),
  ('Harley-Davidson', 'Harley-Davidson Fat Boy 114 / Street Bob'),
  ('Harley-Davidson', 'Harley-Davidson Street Glide / Road Glide'),
  ('Harley-Davidson', 'Harley-Davidson Pan America 1250');
